version: "3"
services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: front
    ports:
      - '5000:3000'
    networks:
      - my_network
networks:
  my_network: 
    driver: bridge